In [68]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

## Basic Understanding of the Dataset

1. Is it a classification problem or a regression problem?
    * Regression problem
2. How many records in the dataset?
    * 1460 training
    * 1459 testing
3. How many variables in the dataset?
    * 81 variables
4. What is the output variable?
    * SalePrice
5. What are the quantitive variables?
    * The quantatitive variables are: 
['1stFlrSF', '2ndFlrSF', '3SsnPorch', 'BedroomAbvGr', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtFullBath', 'BsmtHalfBath', 'BsmtUnfSF', 'EnclosedPorch', 'Fireplaces', 'FullBath', 'GarageArea', 'GarageCars', 'GarageYrBlt', 'GrLivArea', 'HalfBath', 'Id', 'KitchenAbvGr', 'LotArea', 'LotFrontage', 'LowQualFinSF', 'MSSubClass', 'MasVnrArea', 'MiscVal', 'MoSold', 'OpenPorchSF', 'OverallCond', 'OverallQual', 'PoolArea', 'SalePrice', 'ScreenPorch', 'TotRmsAbvGrd', 'TotalBsmtSF', 'WoodDeckSF', 'YearBuilt', 'YearRemodAdd', 'YrSold']
6. What are the qualitative variables?
    * The qualitative variables are: 
['Alley', 'BldgType', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'BsmtQual', 'CentralAir', 'Condition1', 'Condition2', 'Electrical', 'ExterCond', 'ExterQual', 'Exterior1st', 'Exterior2nd', 'Fence', 'FireplaceQu', 'Foundation', 'Functional', 'GarageCond', 'GarageFinish', 'GarageQual', 'GarageType', 'Heating', 'HeatingQC', 'HouseStyle', 'KitchenQual', 'LandContour', 'LandSlope', 'LotConfig', 'LotShape', 'MSZoning', 'MasVnrType', 'MiscFeature', 'Neighborhood', 'PavedDrive', 'PoolQC', 'RoofMatl', 'RoofStyle', 'SaleCondition', 'SaleType', 'Street', 'Utilities']
7. Is there any null values?
BsmtFinSF1         1
BsmtFinSF2         1
BsmtFullBath       2
BsmtHalfBath       2
BsmtUnfSF          1
GarageArea         1
GarageCars         1
GarageYrBlt      159
LotFrontage      486
MasVnrArea        23
SalePrice       1459
TotalBsmtSF        1
8. Is the data clean? (Each variable has the same data type, etc.)
    * Clean

In [69]:
df_train = pd.read_csv('train.csv')
df_test = pd.read_csv('test.csv')
df = pd.concat([df_train, df_test])
df.head()

,1stFlrSF,2ndFlrSF,3SsnPorch,Alley,BedroomAbvGr,BldgType,BsmtCond,BsmtExposure,BsmtFinSF1,BsmtFinSF2,...,SaleType,ScreenPorch,Street,TotRmsAbvGrd,TotalBsmtSF,Utilities,WoodDeckSF,YearBuilt,YearRemodAdd,YrSold
0,856,854,0,NaN,3,1Fam,TA,No,706.0,0.0,...,WD,0,Pave,8,856.0,AllPub,0,2003,2003,2008
1,1262,0,0,NaN,3,1Fam,TA,Gd,978.0,0.0,...,WD,0,Pave,6,1262.0,AllPub,298,1976,1976,2007
2,920,866,0,NaN,3,1Fam,TA,Mn,486.0,0.0,...,WD,0,Pave,6,920.0,AllPub,0,2001,2002,2008
3,961,756,0,NaN,3,1Fam,Gd,No,216.0,0.0,...,WD,0,Pave,7,756.0,AllPub,0,1915,1970,2006
4,1145,1053,0,NaN,4,1Fam,TA,Av,655.0,0.0,...,WD,0,Pave,9,1145.0,AllPub,192,2000,2000,2008

In [70]:
print('The dimension of the training dataset is: ', df_train.shape)
print('The dimension of the testing dataset is: ', df_test.shape)

The dimension of the training dataset is:  (1460, 81)
The dimension of the testing dataset is:  (1459, 80)

In [71]:
df['BsmtCond'].dtype == object

True

In [72]:
df.columns

Index(['1stFlrSF', '2ndFlrSF', '3SsnPorch', 'Alley', 'BedroomAbvGr',
       'BldgType', 'BsmtCond', 'BsmtExposure', 'BsmtFinSF1', 'BsmtFinSF2',
       'BsmtFinType1', 'BsmtFinType2', 'BsmtFullBath', 'BsmtHalfBath',
       'BsmtQual', 'BsmtUnfSF', 'CentralAir', 'Condition1', 'Condition2',
       'Electrical', 'EnclosedPorch', 'ExterCond', 'ExterQual', 'Exterior1st',
       'Exterior2nd', 'Fence', 'FireplaceQu', 'Fireplaces', 'Foundation',
       'FullBath', 'Functional', 'GarageArea', 'GarageCars', 'GarageCond',
       'GarageFinish', 'GarageQual', 'GarageType', 'GarageYrBlt', 'GrLivArea',
       'HalfBath', 'Heating', 'HeatingQC', 'HouseStyle', 'Id', 'KitchenAbvGr',
       'KitchenQual', 'LandContour', 'LandSlope', 'LotArea', 'LotConfig',
       'LotFrontage', 'LotShape', 'LowQualFinSF', 'MSSubClass', 'MSZoning',
       'MasVnrArea', 'MasVnrType', 'MiscFeature', 'MiscVal', 'MoSold',
       'Neighborhood', 'OpenPorchSF', 'OverallCond', 'OverallQual',
       'PavedDrive', 'PoolArea', 'PoolQC', 'RoofMatl', 'RoofStyle',
       'SaleCondition', 'SalePrice', 'SaleType', 'ScreenPorch', 'Street',
       'TotRmsAbvGrd', 'TotalBsmtSF', 'Utilities', 'WoodDeckSF', 'YearBuilt',
       'YearRemodAdd', 'YrSold'],
      dtype='object')

In [73]:
quants = []
qualits = []

for col in df.columns:
    if df[col].dtype == object:
        qualits.append(col)
    else:
        quants.append(col)

print ('The quantatitive variables are: ')
print (quants)
print ()
print ('The qualitative variables are: ')
print (qualits)

The quantatitive variables are:
['1stFlrSF', '2ndFlrSF', '3SsnPorch', 'BedroomAbvGr', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtFullBath', 'BsmtHalfBath', 'BsmtUnfSF', 'EnclosedPorch', 'Fireplaces', 'FullBath', 'GarageArea', 'GarageCars', 'GarageYrBlt', 'GrLivArea', 'HalfBath', 'Id', 'KitchenAbvGr', 'LotArea', 'LotFrontage', 'LowQualFinSF', 'MSSubClass', 'MasVnrArea', 'MiscVal', 'MoSold', 'OpenPorchSF', 'OverallCond', 'OverallQual', 'PoolArea', 'SalePrice', 'ScreenPorch', 'TotRmsAbvGrd', 'TotalBsmtSF', 'WoodDeckSF', 'YearBuilt', 'YearRemodAdd', 'YrSold']

The qualitative variables are:
['Alley', 'BldgType', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'BsmtQual', 'CentralAir', 'Condition1', 'Condition2', 'Electrical', 'ExterCond', 'ExterQual', 'Exterior1st', 'Exterior2nd', 'Fence', 'FireplaceQu', 'Foundation', 'Functional', 'GarageCond', 'GarageFinish', 'GarageQual', 'GarageType', 'Heating', 'HeatingQC', 'HouseStyle', 'KitchenQual', 'LandContour', 'LandSlope', 'LotConfig', 'LotShape', 'MSZoning', 'MasVnrType', 'MiscFeature', 'Neighborhood', 'PavedDrive', 'PoolQC', 'RoofMatl', 'RoofStyle', 'SaleCondition', 'SaleType', 'Street', 'Utilities']

In [74]:
quants_nulls = df[quants].isnull().sum()
quants_nulls.loc[quants_nulls>0]

BsmtFinSF1         1
BsmtFinSF2         1
BsmtFullBath       2
BsmtHalfBath       2
BsmtUnfSF          1
GarageArea         1
GarageCars         1
GarageYrBlt      159
LotFrontage      486
MasVnrArea        23
SalePrice       1459
TotalBsmtSF        1
dtype: int64

In [75]:
quants_null_cols = quants_nulls.loc[quants_nulls>0].index
df[quants_null_cols].head()

,BsmtFinSF1,BsmtFinSF2,BsmtFullBath,BsmtHalfBath,BsmtUnfSF,GarageArea,GarageCars,GarageYrBlt,LotFrontage,MasVnrArea,SalePrice,TotalBsmtSF
0,706.0,0.0,1.0,0.0,150.0,548.0,2.0,2003.0,65.0,196.0,208500.0,856.0
1,978.0,0.0,0.0,1.0,284.0,460.0,2.0,1976.0,80.0,0.0,181500.0,1262.0
2,486.0,0.0,1.0,0.0,434.0,608.0,2.0,2001.0,68.0,162.0,223500.0,920.0
3,216.0,0.0,1.0,0.0,540.0,642.0,3.0,1998.0,60.0,0.0,140000.0,756.0
4,655.0,0.0,1.0,0.0,490.0,836.0,3.0,2000.0,84.0,350.0,250000.0,1145.0

In [76]:
temp = list(quants_null_cols)
temp.remove('SalePrice')

In [85]:
#LotFrontage - mean
temp = list(quants_null_cols)
temp.remove('SalePrice')
temp.remove('LotFrontage')
df.loc[:, temp] = df[temp].fillna(0)

In [86]:
df['LotFrontage'] = df['LotFrontage'].fillna(df['LotFrontage'].mean())

In [87]:
df[quants_null_cols].isnull().sum()

BsmtFinSF1         0
BsmtFinSF2         0
BsmtFullBath       0
BsmtHalfBath       0
BsmtUnfSF          0
GarageArea         0
GarageCars         0
GarageYrBlt        0
LotFrontage        0
MasVnrArea         0
SalePrice       1459
TotalBsmtSF        0
dtype: int64

In [88]:
qualits_nulls = df[qualits].isnull().sum()
qualits_nulls.loc[qualits_nulls>0]

Alley           2721
BsmtCond          82
BsmtExposure      82
BsmtFinType1      79
BsmtFinType2      80
BsmtQual          81
Electrical         1
Exterior1st        1
Exterior2nd        1
Fence           2348
FireplaceQu     1420
Functional         2
GarageCond       159
GarageFinish     159
GarageQual       159
GarageType       157
KitchenQual        1
MSZoning           4
MasVnrType        24
MiscFeature     2814
PoolQC          2909
SaleType           1
Utilities          2
dtype: int64

In [89]:
qualits_null_cols = qualits_nulls.loc[qualits_nulls>0].index
df[qualits_null_cols].head()

,Alley,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinType2,BsmtQual,Electrical,Exterior1st,Exterior2nd,Fence,...,GarageFinish,GarageQual,GarageType,KitchenQual,MSZoning,MasVnrType,MiscFeature,PoolQC,SaleType,Utilities
0,NaN,TA,No,GLQ,Unf,Gd,SBrkr,VinylSd,VinylSd,NaN,...,RFn,TA,Attchd,Gd,RL,BrkFace,NaN,NaN,WD,AllPub
1,NaN,TA,Gd,ALQ,Unf,Gd,SBrkr,MetalSd,MetalSd,NaN,...,RFn,TA,Attchd,TA,RL,None,NaN,NaN,WD,AllPub
2,NaN,TA,Mn,GLQ,Unf,Gd,SBrkr,VinylSd,VinylSd,NaN,...,RFn,TA,Attchd,Gd,RL,BrkFace,NaN,NaN,WD,AllPub
3,NaN,Gd,No,ALQ,Unf,TA,SBrkr,Wd Sdng,Wd Shng,NaN,...,Unf,TA,Detchd,Gd,RL,None,NaN,NaN,WD,AllPub
4,NaN,TA,Av,GLQ,Unf,Gd,SBrkr,VinylSd,VinylSd,NaN,...,RFn,TA,Attchd,Gd,RL,BrkFace,NaN,NaN,WD,AllPub

In [65]:
df[qualits_null_cols] = df[qualits_null_cols].fillna('None')

In [66]:
df.isnull().sum()

1stFlrSF            0
2ndFlrSF            0
3SsnPorch           0
Alley               0
BedroomAbvGr        0
BldgType            0
BsmtCond            0
BsmtExposure        0
BsmtFinSF1          0
BsmtFinSF2          0
BsmtFinType1        0
BsmtFinType2        0
BsmtFullBath        0
BsmtHalfBath        0
BsmtQual            0
BsmtUnfSF           0
CentralAir          0
Condition1          0
Condition2          0
Electrical          0
EnclosedPorch       0
ExterCond           0
ExterQual           0
Exterior1st         0
Exterior2nd         0
Fence               0
FireplaceQu         0
Fireplaces          0
Foundation          0
FullBath            0
                 ...
LotShape            0
LowQualFinSF        0
MSSubClass          0
MSZoning            0
MasVnrArea          0
MasVnrType          0
MiscFeature         0
MiscVal             0
MoSold              0
Neighborhood        0
OpenPorchSF         0
OverallCond         0
OverallQual         0
PavedDrive          0
PoolArea            0
PoolQC              0
RoofMatl            0
RoofStyle           0
SaleCondition       0
SalePrice        1459
SaleType            0
ScreenPorch         0
Street              0
TotRmsAbvGrd        0
TotalBsmtSF         0
Utilities           0
WoodDeckSF          0
YearBuilt           0
YearRemodAdd        0
YrSold              0
Length: 81, dtype: int64

In [67]:
df.to_csv('NoNullData.csv')